language: node_js
dist: bionic
sudo: required
node_js: stable

# Build only master and release tags
branches:
  only:
  - master

env:
  matrix:
  - PATH=$HOME/purescript:$PATH

install:
- export PURS_VERSION=$(wget -q -O - https://github.com/purescript/purescript/releases/latest --server-response --max-redirect 0 2>&1 | sed -n -e 's/.*Location:.*tag\///p')
- wget -O $HOME/purescript.tar.gz https://github.com/purescript/purescript/releases/download/$PURS_VERSION/linux64.tar.gz
- tar -xvf $HOME/purescript.tar.gz -C $HOME/
- chmod a+x $HOME/purescript
- npm install -g spago
- npm install -g purescript
- npm install -g purescript-docs-search

script:
- TAG=$(wget -q -O - https://github.com/purescript/package-sets/releases/latest --server-response --max-redirect 0 2>&1 | sed -n -e 's/.*Location:.*tag\///p')
- node index.js $TAG
- spago install
- set -f
- purs docs $(spago sources)
- purescript-docs-search build-index

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: generated-docs/html
  on:
    branch: master
